const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",

  SET_CURRENTPAGE: "SET_CURRENTPAGE",
  GET_HOUSE: "GET_HOUSE",
  
  SEARCH_HOUSE: "SEARCH_HOUSE",
  SEARCH_HOUSE_SUCCESS: "SEARCH_HOUSE_SUCCESS",
  SEARCH_HOUSE_FAIL: "SEARCH_HOUSE_FAIL",
  CLEAR_SEARCH_PARAMS: "CLEAR_SEARCH_PARAMS",
  
  
  GET_HOUSE_DETAIL: "GET_HOUSE_DETAIL",
  GET_HOUSE_DETAIL_SUCCESS: "GET_HOUSE_DETAIL_SUCCESS",
  GET_HOUSE_DETAIL_FAIL: "GET_HOUSE_DETAIL_FAIL",
  
  CREATE_HOUSE: "CREATE_HOUSE",
  CREATE_HOUSE_SUCCESS: "CREATE_HOUSE_SUCCESS",
  CREATE_HOUSE_FAIL: "CREATE_HOUSE_FAIL",
  
  UPDATE_HOUSE: "UPDATE_HOUSE",
  UPDATE_HOUSE_SUCCESS: "UPDATE_HOUSE_SUCCESS",
  UPDATE_HOUSE_FAIL:"UPDATE_HOUSE_FAIL",
  
  DELETE_HOUSE: "DELETE_HOUSE",
  DELETE_HOUSE_SUCCESS: "DELETE_HOUSE_SUCCESS",
  DELETE_HOUSE_FAIL: "DELETE_HOUSE_FAIL",
};

export default actionTypes;
